spring.application.name=some

spring.datasource.url=jdbc:postgresql://localhost:5432/somedb

spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=your-very-long-random-secret-minimum-64-characters-for-hs512