spring.application.name=some

spring.datasource.url=jdbc:postgresql://localhost:5432/your_db_name

spring.datasource.username=your_pg_username
spring.datasource.password=your_pg_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=your-very-long-random-secret-minimum-64-characters-for-hs512